<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/23
 * Time: 0:42
 */

namespace app\admin\controller;


use think\Controller;

class Category extends Controller
{
    private $obj;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model('Category');
        //$this->obj = new \app\common\model\Category();
    }

    public function index(){
        $parent_id = input('get.parent_id',0,'intval');
        $allCategorys = $this->obj->getNomalCategorys($parent_id,'page');
        return $this->fetch('',['allCategorys' => $allCategorys]);
    }

    /**
     * 数据添加操作
     * @return mixed
     */
    public function add(){
        $categorys = $this->obj->getNomalCategorys();
        return $this->fetch('',['categorys' => $categorys,]);
    }

    /**
     * 编辑页面
     * @return mixed
     */
    public function edit($id = 0){
        if (intval($id) < 1){
            $this->error('参数不合法');
        }
        $id = input('get.id');
        $category = $this->obj->get($id);
        $categorys = $this->obj->getNomalCategorys();
        return $this->fetch('',['category' => $category,'categorys' => $categorys]);
    }
    /**
     * 数据保存操作
     */
    public function save(){
        /**
         * 做一下严格的校验判断
         */
        if (!request()->isPost()){
            $this->error('请求失败');
        }
        $data = input('post.');
        $validate = validate('Category');
        $tag = $validate->scene('add')->check($data);
        if (!$tag){
            $this->error($validate->getError());
        }

        if (!empty($data['id'])){
            return $this->update($data);
        }

        //TODO 数据提交到model层
        $res = $this->obj->add($data);
        if ($res){
            $this->success('新增成功');
        }else{
            $this->error('新增失败');
        }
    }
    public function update($data){
        $tag =$this->obj->save($data,['id' => intval($data['id'])]);
        if ($tag){
            $this->success('更新成功');
        }else{
            $this->error('更新失败');
        }
    }

    //排序逻辑
    public function listorder($id,$listorder){
        $data = ['listorder'=>$listorder];
        $where = ['id'=>intval($id)];
        $tag = $this->obj->save($data,$where);
        $data['referer'] = $_SERVER['HTTP_REFERER'];
        if ($tag){
            return showMsg(1,'success',$data);
        }else{
            return showMsg(0,'排序受阻');
        }
    }

    /**
     * 修改状态
     * @param $id
     * @param $status
     */
    public function status($id,$status=0){
        $where = ['id'=>intval($id)];
        $data = ['status' => $status];
        $tag =$this->obj->save($data,$where);
        if ($tag){
            return showMsg(1,'操作成功');
        }else{
            return showMsg(0,'操作失败');
        }
    }
    public function delete($id){
        $data = ['status' => -1];
        $tag =$this->obj->save($data,['id' => intval($id)]);
        if ($tag){
            $this->success('删除成功');
        }else{
            $this->error('删除失败');
        }
    }
}