<?php
namespace app\api\controller;
use \think\Controller;
/**
 * Created by PhpStorm.
 * User: 百鬼夜行
 * Date: 2017/5/31
 * Time: 15:31
 */
class Category extends Controller
{
    private $obj;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model('Category');
    }
    public function getCategorysByParentId(){
        /**
         * 做一下严格的校验判断
         */
        if (!request()->isPost()){
            return showMsg(0,'网络繁忙，请求失败');
        }else{
            //通过ID获取子类数据
            $category_id = input('post.')['category_id'];
            $category_id = $category_id ? $category_id : null;
            $categorys = $this->obj->getNormalCategorysByParentID($category_id);
            if ($categorys){
                return showMsg(1,'Success',$categorys);
            }else{
                return showMsg(0,'Sorry,没有数据');
            }

        }
    }
}