<?php
namespace app\api\controller;
use \think\Controller;
/**
 * Created by PhpStorm.
 * User: 百鬼夜行
 * Date: 2017/5/31
 * Time: 15:31
 */
class City extends Controller
{
    private $obj;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model('City');
    }
    public function getCitysByParentId(){
        /**
         * 做一下严格的校验判断
         */
        if (!request()->isPost()){
            return showMsg(0,'网络繁忙，请求失败');
        }else{
            //通过ID获取二级城市
            $city_id = input('post.')['city_id'];
            $city_id = $city_id ? $city_id : null;
            $citys = $this->obj->getNormalCitysByParentID($city_id);
            if ($citys){
                return showMsg(1,'Success',$citys);
            }else{
                return showMsg(0,'Sorry,没有数据');
            }

        }
    }
}